### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by colesnicov** [ttsiodras/ATtiny85_currentMeter#1]
Hello, It's look good. You can provide Schematic? please.

**Comment by ttsiodras** [comment]
Hi. This was a very simple circuit, so I just breadboarded it and then transferred it to perfboard. The closest I have to a schematic is the extensive documentation I wrote inside the comments - here: https://github.com/ttsiodras/ATtiny85_currentMeter/blob/master/Attiny85CurrentMeter.ino#L2 - have a look.
